MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN
    DEPTH: 50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: avgpool
    NECK_FEAT: before
    CLS_LAYER: linear

  LOSSES:
    NAME: ("CE", "Trip",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  REA:
    ENABLED: True
    PROB: 0.5
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True   #SYSU_MM01为False，RedDB为True
  BiCAMERA_WAY: False  #SYSU_MM01为True，RegDb为False
  NUM_INSTANCE: 8
  NUM_WORKERS: 8

SOLVER:
  FP16_ENABLED: True
  OPT: Adam
  MAX_EPOCH: 200
  BASE_LR: 0.0006
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 128


  SCHED: MultiStepLR
  STEPS: [30, 60, 120]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 1000

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True
